#!/bin/bash
#SBATCH --account=hologenomics         # Project Account
#SBATCH --partition=hologenomics 
#SBATCH --mem 1G
#SBATCH -c 1
#SBATCH -t 1:00:00
#SBATCH -J pa03_blibrarynumber
#SBATCH -o stdout_pa03A.txt
#SBATCH -e stderr_pa03A.txt

# get working directory
WD=$(pwd)

#remove any previous output directories generated by the r-script you are about to run
# rm -rf DADA2_extracted_samples_nochim
# rm -rf DADA2_extracted_samples_raw

##source activate YOUR_CONDA_ENV
##source /com/extra/R/3.5.0/load.sh
#load modules required
module purge
#module load python/v2.7.12
#module load cutadapt/v1.11
#module load vsearch/v2.8.0


# load the R module 'dada2' package for R requires R v3.4
#module load R/v3.4.3
# In July-2021 dada2 is installed with R v.4.0.2
#module load R/v4.0.2
# run the R code
./part03B_bash_make_sbatch_and_dada2_end_inR_v01.sh